{% set name = "azure-core" %}
{% set version = "1.30.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f3a7883ef184722f6bd997262eddaf80cfe7e5b3e0caaaf8db1695695893d35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - requests >=2.21.0
    - six >=1.11.0
    - typing-extensions >=4.6.0

test:
  imports:
    - azure.core
    - azure.core.pipeline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/core/azure-core
  summary: Microsoft Azure Core Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - TomAugspurger
    - marcelotrevisani
